export const citesObj:any = {
   1: { textEng: '', textUa: 'Я пішов за своїм серцем, і воно привело мене на місяць' },
   2: { textEng: '', textUa: 'Місяць став танцюристом на цьому фестивалі подій' },
   3: { textEng: '', textUa: 'дотягнутися до місяця' },
   4: { textEng: 'Each night the moon kisses secretly the lover who counts the stars', textUa: 'Кожної ночі місяць таємно цілує того, хто рахує зірки' },
   5: { textEng: 'The moon is magic for the soul... and light for the senses', textUa: 'Місяць - це магія для душі... і світло для почуттів' },
   6: { textEng: 'Be the star that shines as bright as the moon', textUa: 'Будь зіркою, яка сяє так яскраво, як місяць' },
   7: { textEng: 'One day, to the moon, I wrote a long long letter. Thought it wasn\'t brighter then you. I lit a small candle', textUa: 'Одного разу до місяця я написав довгого листа. Думав, що це не яскравіше, ніж ти. Я запалив маленьку свічку' },
   8: { textEng: 'The moon is magic for the soul', textUa: 'Місяць - це чари для душі' },
   9: { textEng: 'The moon recognises star which loves you', textUa: 'Місяць розпізнає зірку, яка тебе любить' },
   10: { textEng: 'The moon is always full even when we can\'t see it', textUa: 'Місяць завжди повний, навіть коли ми його не бачимо' },
   11: { textEng: 'The night walked down the sky with the moon in her hand', textUa: 'Ніч йшла по небу з місяцем у руці' },
   12: { textEng: 'to the moon and never back', textUa: 'на місяць і ніколи назад' },
   13: { textEng: 'Thank you for telling me , i deserve the moon', textUa: 'Дякую, що сказав мені, я заслуговую на місяць' },
   14: { textEng: 'In presence of the moon nobody sees stars', textUa: 'У присутності місяця ніхто не бачить зірок' },
   15: { textEng: 'Moonlight is the proof that there will always be light in darkness', textUa: 'Місячне світло є доказом того, що в темряві завжди буде світло' },
   16: { textEng: 'Sometimes the moon is all i have', textUa: 'Іноді місяць - це все, що я маю' },
   17: { textEng: 'The sun watches what i do, but the moon knows all my secrets', textUa: 'Сонце стежить за тим, що я роблю, але місяць знає всі мої секрети' },
   18: { textEng: "If you're looking for me I'll be under the moonlight", textUa: 'Якщо ти мене шукаєш, я буду під місячним світлом' },
   19: { textEng: 'Fly me to the moon, let me play among the stars', textUa: 'Лети зі мною на місяць, дозволь мені пограти із зірками' },
   20: { textEng: "Don't worry the darkness will fade away soon, Till then let's appreciate this beautiful moon", textUa: 'Не хвилюйся, темрява скоро розійдеться, а до того часу давайте цінувати цей прекрасний місяць' },
   21: { textEng: 'Just smile like half moon', textUa: 'Просто посміхайся, як півмісяць' },
   22: { textEng: 'People were like the moon part. Part of her always hidden away', textUa: 'Люди були як частина місяця. Частина її завжди прихована' },
   23: { textEng: 'Never stop looking up', textUa: 'Ніколи не переставайте дивитися вгору' },
   24: { textEng: "I'll hug you like the night hugs the moon", textUa: 'Я обійму тебе, як ніч обіймає місяць' },
   25: { textEng: 'Selenophile - a person who leves the moon', textUa: 'Селенофіл - людина, яка любить місяць' },
   26: { textEng: 'But i love you so much more than just to the moon and back', textUa: 'Але я люблю тебе набагато більше, ніж просто до місяця і назад' },
   27: { textEng: 'Who has a night in  his life, the moon will come in his life', textUa: 'Хто має ніч у своєму житті ніч, до того прийде місяць' },
   28: { textEng: 'In my dream, I\m with you', textUa: 'Уві сні я з тобою' },
   29: { textEng: "Lovers are patient and know that the moon needs time to become full", textUa: 'Закохані терплячі і знають, що місяцю потрібен час, щоб стати повним' },
   30: { textEng: 'Scars can be wonderful too', textUa: 'Шрами також можуть бути чудовими' },
   31: { textEng: "The moon will guide you through the night with its brightness, but it will always live in the dark to be seen", textUa: "Місяць буде вести вас крізь ніч своєю яскравістю, але вiн завжди буде жити в темряві, щоб його бачили" },
   32: { textEng: "Full moon is a good fisherman, every eyes are easily caught in his net", textUa: "Повний місяць — добрий рибалка, всяке око в його сіті легко ловиться" },
   33: { textEng: "The moon is a friend for the lonesome to talk to", textUa: "Місяць — друг для самотніх, з яким можна поговорити" },
   34: { textEng: "The moon is the reflection of your heart and moonlight is the twinkle of your love", textUa: "Місяць - це відображення твого серця, а місячне світло - мерехтіння твоєї любові" },
   35: { textEng: "The moon is the first milestone on the road to the stars", textUa: "Місяць – перша зупинка на шляху до зірок" },
   36: { textEng: "Don't tell me the sky's the limit when there are footprints on the moon", textUa: "Не кажіть мені, що небо є межею, коли на місяці є сліди" },
   37: { textEng: "Drag me to the moon, to catch a star and seizes its brilliance as I'm swept up in amorphous dust", textUa: "Потягни мене на місяць, щоб зловити зірку та схопити її блиск, коли мене замітає аморфний пил" },
   38: { textEng: "Moonlight is sculpture; sunlight is painting", textUa: "Місячне світло — скульптура; сонячне світло малює" },
   39: { textEng: "The moon looks upon many night flowers; the night flowers see but one moon", textUa: "Місяць дивиться на багато нічних квітів; нічні квіти бачать лише один місяць" },
   40: { textEng: "You are the sun. You bring warmth, laughter, and joy-but he is the moon. He draws me into a world of mystery that i have never known", textUa: "Ти сонце. Ти приносиш тепло, сміх і радість, але він — місяць. Він затягує мене у світ таємниць, якого я ніколи не знав" },
   // 41: { textEng: "", textUa: "" },
   // 42: { textEng: "", textUa: "" },
   // 43: { textEng: "", textUa: "" },
   // 44: { textEng: "", textUa: "" },
   // 45: { textEng: "", textUa: "" },
   // 46: { textEng: "", textUa: "" },
   // 47: { textEng: "", textUa: "" },
   // 48: { textEng: "", textUa: "" },
   // 49: { textEng: "", textUa: "" },
   // 50: { textEng: "", textUa: "" },

}